server:
  port: 8080

spring:
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eating_pizza?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache:
    type: redis
    redis:
#      time-to-live: 3600 # 데이터 유지 시간(sec)
      cache-null-values: true # null 캐싱 여부
      host: localhost
      port: 6379